CREATE TABLE [dbo].[Post]
(
	[PostKey] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[PostGuid] UNIQUEIDENTIFIER NOT NULL,
	[Title] NVARCHAR(300) NULL,
	[SubTitle] NVARCHAR(600) NULL,
	[BrowserTitle] NVARCHAR(MAX) NOT NULL,
	[AuthorKey] INT NOT NULL,
	[Url] NVARCHAR(MAX) NOT NULL,
	[SortUrl] NVARCHAR(1000) NULL,
	[MainContentImageUrl] NVARCHAR(MAX) NULL,
	[MainContentImageSubtitle] NVARCHAR(1000) NULL,
	[Content] NVARCHAR(MAX) NULL,
	[CategoryKey] INT NULL,
	[IsPublished] TINYINT NOT NULL DEFAULT(0),
	[IsActive] TINYINT NOT NULL DEFAULT(1),
	[IsDeleted] TINYINT NOT NULL DEFAULT(0),
	[BlogKey] INT NOT NULL,
	[Views] INT NOT NULL DEFAULT(0),
	[Votes] INT NOT NULL DEFAULT(0),
	[Previous] NVARCHAR(1000) NULL,
	[Next] NVARCHAR(1000) NULL,
	[CreatedAt] DATE NOT NULL DEFAULT(getdate()), 
    [CreatedBy] INT NOT NULL, 
    [UpdatedAt] DATE NOT NULL DEFAULT(getdate()), 
    [UpdatedBy] INT NOT NULL, 
    CONSTRAINT [FK_PostCreatedBy] FOREIGN KEY (CreatedBy) REFERENCES [User]([UserKey]),
    CONSTRAINT [FK_PostUpdatedBy] FOREIGN KEY (UpdatedBy) REFERENCES [User]([UserKey])
)
